[2025-04-30T23:38:14.639+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.stream_flag_data manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-04-30T23:38:14.651+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.stream_flag_data manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-04-30T23:38:14.651+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-04-30T23:38:14.667+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): stream_flag_data> on 2025-04-30 23:04:13.923792+00:00
[2025-04-30T23:38:14.672+0000] {standard_task_runner.py:60} INFO - Started process 16926 to run task
[2025-04-30T23:38:14.675+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'stream_flag_data', 'manual__2025-04-30T23:04:13.923792+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpllto5y9t']
[2025-04-30T23:38:14.677+0000] {standard_task_runner.py:88} INFO - Job 146: Subtask stream_flag_data
[2025-04-30T23:38:14.777+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.stream_flag_data manual__2025-04-30T23:04:13.923792+00:00 [running]> on host e4f2445a264f
[2025-04-30T23:38:14.956+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='stream_flag_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T23:04:13.923792+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T23:04:13.923792+00:00'
[2025-04-30T23:38:14.959+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 197, in stream_flag_data
    long_rides = df.filter(pl.col('duration_seconds') > 2700)
AttributeError: 'str' object has no attribute 'filter'
[2025-04-30T23:38:14.988+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=bikeshare_etl_pipeline, task_id=stream_flag_data, execution_date=20250430T230413, start_date=20250430T233814, end_date=20250430T233814
[2025-04-30T23:38:15.012+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 146 for task stream_flag_data ('str' object has no attribute 'filter'; 16926)
[2025-04-30T23:38:15.047+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T23:38:15.134+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
