[2025-05-02T00:10:09.755+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.load_log_to_bucket manual__2025-05-02T00:04:26.059841+00:00 [queued]>
[2025-05-02T00:10:09.785+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.load_log_to_bucket manual__2025-05-02T00:04:26.059841+00:00 [queued]>
[2025-05-02T00:10:09.786+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2025-05-02T00:10:09.817+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_log_to_bucket> on 2025-05-02 00:04:26.059841+00:00
[2025-05-02T00:10:09.830+0000] {standard_task_runner.py:60} INFO - Started process 2331 to run task
[2025-05-02T00:10:09.835+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'load_log_to_bucket', 'manual__2025-05-02T00:04:26.059841+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpfkcvmm2m']
[2025-05-02T00:10:09.839+0000] {standard_task_runner.py:88} INFO - Job 245: Subtask load_log_to_bucket
[2025-05-02T00:10:10.037+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.load_log_to_bucket manual__2025-05-02T00:04:26.059841+00:00 [running]> on host 80c5452bd0a4
[2025-05-02T00:10:10.439+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_log_to_bucket' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:04:26.059841+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T00:04:26.059841+00:00'
[2025-05-02T00:10:10.445+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 219, in load_log_to_bucket
    log_files = [f for f in os.listdir(folder_path) if f.lower().endswith('.log')]
NotADirectoryError: [Errno 20] Not a directory: '/opt/airflow/data/bike_rides_02-05-2025.log'
[2025-05-02T00:10:10.514+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=load_log_to_bucket, execution_date=20250502T000426, start_date=20250502T001009, end_date=20250502T001010
[2025-05-02T00:10:10.543+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 245 for task load_log_to_bucket ([Errno 20] Not a directory: '/opt/airflow/data/bike_rides_02-05-2025.log'; 2331)
[2025-05-02T00:10:10.578+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-02T00:10:10.745+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
