[2025-04-30T23:34:03.366+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.transform_data manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-04-30T23:34:03.380+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.transform_data manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-04-30T23:34:03.381+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2025-04-30T23:34:03.396+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): transform_data> on 2025-04-30 23:04:13.923792+00:00
[2025-04-30T23:34:03.402+0000] {standard_task_runner.py:60} INFO - Started process 16539 to run task
[2025-04-30T23:34:03.404+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'transform_data', 'manual__2025-04-30T23:04:13.923792+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpbrbz_9er']
[2025-04-30T23:34:03.406+0000] {standard_task_runner.py:88} INFO - Job 139: Subtask transform_data
[2025-04-30T23:34:03.580+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.transform_data manual__2025-04-30T23:04:13.923792+00:00 [running]> on host e4f2445a264f
[2025-04-30T23:34:04.266+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T23:04:13.923792+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T23:04:13.923792+00:00'
[2025-04-30T23:34:05.648+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 140, in transform_data
    data = data.with_columns([
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/dataframe/frame.py", line 9154, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/lazyframe/frame.py", line 2053, in collect
    return wrap_df(ldf.collect(callback))
polars.exceptions.InvalidOperationError: conversion from `str` to `datetime[μs]` failed in column 'started_at' for 8622 out of 8622 values: ["2022-12-05 14:43:15", "2022-12-03 13:26:41", … "2022-12-11 13:11:58"]

You might want to try:
- setting `strict=False` to set values that cannot be converted to `null`
- using `str.strptime`, `str.to_date`, or `str.to_datetime` and providing a format string
[2025-04-30T23:34:05.695+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=transform_data, execution_date=20250430T230413, start_date=20250430T233403, end_date=20250430T233405
[2025-04-30T23:34:05.725+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 139 for task transform_data (conversion from `str` to `datetime[μs]` failed in column 'started_at' for 8622 out of 8622 values: ["2022-12-05 14:43:15", "2022-12-03 13:26:41", … "2022-12-11 13:11:58"]

You might want to try:
- setting `strict=False` to set values that cannot be converted to `null`
- using `str.strptime`, `str.to_date`, or `str.to_datetime` and providing a format string; 16539)
[2025-04-30T23:34:05.744+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T23:34:05.897+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
