[2025-04-30T23:29:33.574+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.transform_data manual__2025-04-30T22:38:47.303758+00:00 [queued]>
[2025-04-30T23:29:33.587+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.transform_data manual__2025-04-30T22:38:47.303758+00:00 [queued]>
[2025-04-30T23:29:33.588+0000] {taskinstance.py:2193} INFO - Starting attempt 9 of 10
[2025-04-30T23:29:33.607+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): transform_data> on 2025-04-30 22:38:47.303758+00:00
[2025-04-30T23:29:33.615+0000] {standard_task_runner.py:60} INFO - Started process 16070 to run task
[2025-04-30T23:29:33.619+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'transform_data', 'manual__2025-04-30T22:38:47.303758+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpcggyulz4']
[2025-04-30T23:29:33.621+0000] {standard_task_runner.py:88} INFO - Job 136: Subtask transform_data
[2025-04-30T23:29:33.761+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.transform_data manual__2025-04-30T22:38:47.303758+00:00 [running]> on host e4f2445a264f
[2025-04-30T23:29:33.982+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T22:38:47.303758+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T22:38:47.303758+00:00'
[2025-04-30T23:29:34.744+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 155, in transform_data
    filename=df.write_parquet(f"{CURRENT_DATE}_{file_name}",separator="," ),
TypeError: write_parquet() got an unexpected keyword argument 'separator'
[2025-04-30T23:29:34.774+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=transform_data, execution_date=20250430T223847, start_date=20250430T232933, end_date=20250430T232934
[2025-04-30T23:29:34.798+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 136 for task transform_data (write_parquet() got an unexpected keyword argument 'separator'; 16070)
[2025-04-30T23:29:34.835+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T23:29:34.901+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
