[2025-04-30T23:27:57.863+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.transform_data manual__2025-04-30T22:38:47.303758+00:00 [queued]>
[2025-04-30T23:27:57.880+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.transform_data manual__2025-04-30T22:38:47.303758+00:00 [queued]>
[2025-04-30T23:27:57.881+0000] {taskinstance.py:2193} INFO - Starting attempt 7 of 8
[2025-04-30T23:27:57.903+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): transform_data> on 2025-04-30 22:38:47.303758+00:00
[2025-04-30T23:27:57.912+0000] {standard_task_runner.py:60} INFO - Started process 15906 to run task
[2025-04-30T23:27:57.916+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'transform_data', 'manual__2025-04-30T22:38:47.303758+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpl6cl77_d']
[2025-04-30T23:27:57.919+0000] {standard_task_runner.py:88} INFO - Job 134: Subtask transform_data
[2025-04-30T23:27:58.056+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.transform_data manual__2025-04-30T22:38:47.303758+00:00 [running]> on host e4f2445a264f
[2025-04-30T23:27:58.333+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T22:38:47.303758+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T22:38:47.303758+00:00'
[2025-04-30T23:27:59.156+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 155, in transform_data
    filename=df.write_csv(f"{CURRENT_DATE}_{file_name}",separator="," ),
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/dataframe/frame.py", line 2892, in write_csv
    self._df.write_csv(
polars.exceptions.ComputeError: datatype duration[μs] cannot be written to csv
[2025-04-30T23:27:59.205+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=transform_data, execution_date=20250430T223847, start_date=20250430T232757, end_date=20250430T232759
[2025-04-30T23:27:59.242+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 134 for task transform_data (datatype duration[μs] cannot be written to csv; 15906)
[2025-04-30T23:27:59.292+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T23:27:59.373+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
