[2025-04-30T19:55:53.615+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.unzip_file manual__2025-04-30T19:19:29.801074+00:00 [queued]>
[2025-04-30T19:55:53.629+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.unzip_file manual__2025-04-30T19:19:29.801074+00:00 [queued]>
[2025-04-30T19:55:53.630+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-04-30T19:55:53.645+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): unzip_file> on 2025-04-30 19:19:29.801074+00:00
[2025-04-30T19:55:53.652+0000] {standard_task_runner.py:60} INFO - Started process 4181 to run task
[2025-04-30T19:55:53.655+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'unzip_file', 'manual__2025-04-30T19:19:29.801074+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp_3t9sg5e']
[2025-04-30T19:55:53.657+0000] {standard_task_runner.py:88} INFO - Job 71: Subtask unzip_file
[2025-04-30T19:55:53.791+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.unzip_file manual__2025-04-30T19:19:29.801074+00:00 [running]> on host e4f2445a264f
[2025-04-30T19:55:54.046+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='unzip_file' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T19:19:29.801074+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T19:19:29.801074+00:00'
[2025-04-30T19:55:54.073+0000] {base.py:83} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2025-04-30T19:55:54.074+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from extra.
[2025-04-30T19:55:54.637+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 77, in unzip_file
    zip_bytes = s3_hook.read_key(key=zip_key, bucket_name=MINIO_BUCKET_RAW)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 137, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 971, in read_key
    return obj.get()["Body"].read().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 22: invalid continuation byte
[2025-04-30T19:55:54.683+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=bikeshare_etl_pipeline, task_id=unzip_file, execution_date=20250430T191929, start_date=20250430T195553, end_date=20250430T195554
[2025-04-30T19:55:54.712+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 71 for task unzip_file ('utf-8' codec can't decode byte 0xc9 in position 22: invalid continuation byte; 4181)
[2025-04-30T19:55:54.753+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T19:55:54.875+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
