[2025-05-01T00:01:41.235+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-05-01T00:01:41.247+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-05-01T00:01:41.248+0000] {taskinstance.py:2193} INFO - Starting attempt 12 of 13
[2025-05-01T00:01:41.263+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_cleaned_data_to_minio> on 2025-04-30 23:04:13.923792+00:00
[2025-05-01T00:01:41.268+0000] {standard_task_runner.py:60} INFO - Started process 18479 to run task
[2025-05-01T00:01:41.272+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'load_cleaned_data_to_minio', 'manual__2025-04-30T23:04:13.923792+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpv_eshdo7']
[2025-05-01T00:01:41.274+0000] {standard_task_runner.py:88} INFO - Job 161: Subtask load_cleaned_data_to_minio
[2025-05-01T00:01:41.378+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [running]> on host e4f2445a264f
[2025-05-01T00:01:41.570+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_cleaned_data_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T23:04:13.923792+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T23:04:13.923792+00:00'
[2025-05-01T00:01:41.595+0000] {base.py:83} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2025-05-01T00:01:41.596+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from extra.
[2025-05-01T00:01:41.811+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 174, in load_cleaned_data_to_minio
    print(s3.get_key(MINIO_BUCKET_CLEANED, s3_key))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 137, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 954, in get_key
    obj.load(**sanitize_extra_args())
  File "/home/airflow/.local/lib/python3.8/site-packages/boto3/resources/factory.py", line 565, in do_action
    response = action(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 946, in _make_api_call
    api_params = self._emit_api_params(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 1072, in _emit_api_params
    self.meta.events.emit(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/handlers.py", line 288, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "30-04-2025/capitalbikeshare-tripdata.parquet": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2025-05-01T00:01:41.840+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=load_cleaned_data_to_minio, execution_date=20250430T230413, start_date=20250501T000141, end_date=20250501T000141
[2025-05-01T00:01:41.857+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 161 for task load_cleaned_data_to_minio (Parameter validation failed:
Invalid bucket name "30-04-2025/capitalbikeshare-tripdata.parquet": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"; 18479)
[2025-05-01T00:01:41.885+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-01T00:01:41.927+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
