[2025-05-01T00:25:13.235+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-05-01T00:25:13.249+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-05-01T00:25:13.250+0000] {taskinstance.py:2193} INFO - Starting attempt 21 of 22
[2025-05-01T00:25:13.272+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_cleaned_data_to_minio> on 2025-04-30 23:04:13.923792+00:00
[2025-05-01T00:25:13.281+0000] {standard_task_runner.py:60} INFO - Started process 19933 to run task
[2025-05-01T00:25:13.286+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'load_cleaned_data_to_minio', 'manual__2025-04-30T23:04:13.923792+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpa6odx9xw']
[2025-05-01T00:25:13.289+0000] {standard_task_runner.py:88} INFO - Job 170: Subtask load_cleaned_data_to_minio
[2025-05-01T00:25:13.481+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [running]> on host e4f2445a264f
[2025-05-01T00:25:13.700+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_cleaned_data_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T23:04:13.923792+00:00' AIRFLOW_CTX_TRY_NUMBER='21' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T23:04:13.923792+00:00'
[2025-05-01T00:25:13.735+0000] {base.py:83} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2025-05-01T00:25:13.737+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from extra.
[2025-05-01T00:25:13.753+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 186, in load_cleaned_data_to_minio
    "endpoint_url": MINIO_ENDPOINT_URL,  # If you're using MinIO, provide the endpoint URL
NameError: name 'MINIO_ENDPOINT_URL' is not defined
[2025-05-01T00:25:13.790+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=load_cleaned_data_to_minio, execution_date=20250430T230413, start_date=20250501T002513, end_date=20250501T002513
[2025-05-01T00:25:13.813+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 170 for task load_cleaned_data_to_minio (name 'MINIO_ENDPOINT_URL' is not defined; 19933)
[2025-05-01T00:25:13.860+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-01T00:25:13.937+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
