[2025-04-30T22:47:42.032+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.upload_files_to_minio manual__2025-04-30T22:38:47.303758+00:00 [queued]>
[2025-04-30T22:47:42.051+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.upload_files_to_minio manual__2025-04-30T22:38:47.303758+00:00 [queued]>
[2025-04-30T22:47:42.053+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2025-04-30T22:47:42.071+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): upload_files_to_minio> on 2025-04-30 22:38:47.303758+00:00
[2025-04-30T22:47:42.076+0000] {standard_task_runner.py:60} INFO - Started process 13250 to run task
[2025-04-30T22:47:42.079+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'upload_files_to_minio', 'manual__2025-04-30T22:38:47.303758+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp5wrstcw5']
[2025-04-30T22:47:42.082+0000] {standard_task_runner.py:88} INFO - Job 102: Subtask upload_files_to_minio
[2025-04-30T22:47:42.218+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.upload_files_to_minio manual__2025-04-30T22:38:47.303758+00:00 [running]> on host e4f2445a264f
[2025-04-30T22:47:42.574+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='upload_files_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T22:38:47.303758+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T22:38:47.303758+00:00'
[2025-04-30T22:47:42.576+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 104, in upload_files_to_minio
    first_csv = os.path.join(folder_path, csv_files[0])
  File "/usr/local/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2025-04-30T22:47:42.619+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=bikeshare_etl_pipeline, task_id=upload_files_to_minio, execution_date=20250430T223847, start_date=20250430T224742, end_date=20250430T224742
[2025-04-30T22:47:42.654+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 102 for task upload_files_to_minio (expected str, bytes or os.PathLike object, not NoneType; 13250)
[2025-04-30T22:47:42.693+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T22:47:42.765+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
