[2025-04-30T22:50:26.326+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.upload_files_to_minio manual__2025-04-30T22:49:00.476281+00:00 [queued]>
[2025-04-30T22:50:26.339+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.upload_files_to_minio manual__2025-04-30T22:49:00.476281+00:00 [queued]>
[2025-04-30T22:50:26.340+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-04-30T22:50:26.368+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): upload_files_to_minio> on 2025-04-30 22:49:00.476281+00:00
[2025-04-30T22:50:26.373+0000] {standard_task_runner.py:60} INFO - Started process 13428 to run task
[2025-04-30T22:50:26.378+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'upload_files_to_minio', 'manual__2025-04-30T22:49:00.476281+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpcetsmqhv']
[2025-04-30T22:50:26.382+0000] {standard_task_runner.py:88} INFO - Job 112: Subtask upload_files_to_minio
[2025-04-30T22:50:26.504+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.upload_files_to_minio manual__2025-04-30T22:49:00.476281+00:00 [running]> on host e4f2445a264f
[2025-04-30T22:50:26.726+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='upload_files_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T22:49:00.476281+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T22:49:00.476281+00:00'
[2025-04-30T22:50:26.728+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 104, in upload_files_to_minio
    first_csv = os.path.join(folder_path, csv_files[0])
  File "/usr/local/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2025-04-30T22:50:26.772+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=bikeshare_etl_pipeline, task_id=upload_files_to_minio, execution_date=20250430T224900, start_date=20250430T225026, end_date=20250430T225026
[2025-04-30T22:50:26.791+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 112 for task upload_files_to_minio (expected str, bytes or os.PathLike object, not NoneType; 13428)
[2025-04-30T22:50:26.830+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T22:50:26.896+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
