[2025-04-30T22:41:36.258+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.download_and_unzip_locally manual__2025-04-30T22:38:47.303758+00:00 [queued]>
[2025-04-30T22:41:36.270+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.download_and_unzip_locally manual__2025-04-30T22:38:47.303758+00:00 [queued]>
[2025-04-30T22:41:36.270+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2025-04-30T22:41:36.284+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): download_and_unzip_locally> on 2025-04-30 22:38:47.303758+00:00
[2025-04-30T22:41:36.289+0000] {standard_task_runner.py:60} INFO - Started process 12883 to run task
[2025-04-30T22:41:36.294+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'download_and_unzip_locally', 'manual__2025-04-30T22:38:47.303758+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpc8v5sqn_']
[2025-04-30T22:41:36.297+0000] {standard_task_runner.py:88} INFO - Job 86: Subtask download_and_unzip_locally
[2025-04-30T22:41:36.477+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.download_and_unzip_locally manual__2025-04-30T22:38:47.303758+00:00 [running]> on host e4f2445a264f
[2025-04-30T22:41:36.690+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='download_and_unzip_locally' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T22:38:47.303758+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T22:38:47.303758+00:00'
[2025-04-30T22:42:00.086+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 88, in download_and_unzip_locally
    with ZipFile(zip_path, 'r') as zip_ref:
  File "/usr/local/lib/python3.8/zipfile.py", line 1253, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/30-04-2025_capitalbikeshare-tripdata.zip'
[2025-04-30T22:42:00.127+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=download_and_unzip_locally, execution_date=20250430T223847, start_date=20250430T224136, end_date=20250430T224200
[2025-04-30T22:42:00.149+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 86 for task download_and_unzip_locally ([Errno 2] No such file or directory: '/opt/airflow/dags/data/30-04-2025_capitalbikeshare-tripdata.zip'; 12883)
[2025-04-30T22:42:00.156+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T22:42:00.229+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
